# We use shippable for "DEVELOP"
image: opalj/sbt_scala_javafx
clone:
  depth: 1

pipelines:
  default:
    - step:
        script:
          - sbt projects
  branches:
    feature/*:
      - step:
          script:
            - sbt test
