image: opalj/sbt_scala_javafx
clone:
    depth: 1

pipelines:
    default:
    - step:
        script:
            - sbt it:compile test:compile

    branches:
        '*':
            - sbt compileAll
            - sbt test
