name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  it-test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Run Integration Tests
      run: sbt -J-Xmx40G cleanBuild it:test
